wechat:
  config:
    appID: wxae5be46991248659
    appsecret: 736af0067fe2d85c437bf58e618bb5ee
    accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxae5be46991248659&secret=736af0067fe2d85c437bf58e618bb5ee
    tempID: Kx_VJGoV4BT2T5gt0Pq9l8dZr5cs88FnIzme75t2s3c
    openID:
      me: ofEgn6HeCXqHc5DZcR_FmDMlKcjs
      special: ofEgn6GNS_cPCTCKrWCUXAzdVSdc
    templateMsgUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
    relationStartDate: 2022-12-10
    menstruationDay: 5
openWeather:
  config:
    url: https://api.openweathermap.org/data/2.5/weather?lat=49.48&lon=-97.9&appid=d686bb6dd05b39f5410278910944e60d&lang=zh_cn

dailyMsg:
  config:
    url: https://apis.tianapi.com/caihongpi/index?key=12594a36b2365fb13c9e35d49829d45d
