wechat:
  config:
    appID: wxae5be46991248659
    appsecret: 736af0067fe2d85c437bf58e618bb5ee
    accessTokenUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=wxae5be46991248659&secret=736af0067fe2d85c437bf58e618bb5ee
    tempID: 3rMrxKV3r2i0v-Tm06esYmNOk2sBJakR_gxVZJoZmFY
    openID: ofEgn6HeCXqHc5DZcR_FmDMlKcjs
    templateMsgUrl: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=